---
abstract: 'Send log messages to Gearman workers.'
author:
  - 'Johannes Plunien <plu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Handler-Output-Gearman
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Carp::Clan: 0
  Gearman::XS: 0.6
  Log::Handler: 0.62
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01003
